### ISSUE TITLE
Not found `DACE_PATH_STATS_JSON` in `process.env`

### ISSUE THREAD

**Issue by zhongzhi107** [dacejs/dace#13]
**Describe the bug**
运行 `npm run build && node dist/server.js` 报错 Not found `DACE_PATH_STATS_JSON` in `process.env`

**To Reproduce**
1. 运行 `npm run build && node dist/server.js`
2. 浏览网页 `http://localhost:3000`
3. 页面一直loading
4. 控制台报错
```
(node:24411) UnhandledPromiseRejectionWarning: Error: Not found `DACE_PATH_STATS_JSON` in `process.env`
    at exports.default (/Users/zhi.zhong/workspace/q/h-touch-transaction/node_modules/dace/dist/runtime/utils/renderTags.js:22:11)
    at /Users/zhi.zhong/workspace/q/h-touch-transaction/dist/server.js:1:61363
    at tryCatch (/Users/zhi.zhong/workspace/q/h-touch-transaction/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/zhi.zhong/workspace/q/h-touch-transaction/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/zhi.zhong/workspace/q/h-touch-transaction/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/zhi.zhong/workspace/q/h-touch-transaction/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/zhi.zhong/workspace/q/h-touch-transaction/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
期望网页能正常显示

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser Version: [chrome 71.0.3578.98（正式版本） （64 位）]
 - Node: [6.6.0]
 - Webpack Version: [4.16.1]
 - Dace Version: [2.0.0-alpha.12]

**Additional context**
`npm start` 正常

**Comment by zhongzhi107** [comment]
#### 问题分析
Dace 运行时代码中用到了 `process.env` 变量，这些变量是 webpack 打包时通过 `webpack.DefinePlugin` 传入到编译后的代码中，由于 webpack 配置了 `externals`，编译之后 require 对 node_modules 中所有的引用（包含 dace ）都是动态引用，这就会导致 dace/dist/runtime 中的代码取不到 `process.env` (均为 undefined ），从而产生上述错误。
#### 解决方法
修改 webpack 配置，将 dace 从 externals 中排除，这样，Webpack 打包时将 dace 一起打入 `dist/server.js`，保证编译过程能正常注入 `process.env.DACE_PATH_STATS_JSON`，避免在运行 server.js 动态 require。
